GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/3

###
GET http://localhost:3001/api/persons/65edf641c2243b6a5dfad75b
###
DELETE http://localhost:3001/api/persons/4

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name":"test name",
    "number": "test number"
}