GET http://localhost:3001/api/blogs/
###
GET http://localhost:3001/api//blogs/3

###
GET http://localhost:3001/api//blogs/65edf641c2243b6a5dfad75b

###
DELETE http://localhost:3001/api//blogs/65edf641c2243b6a5dfad75b


###
DELETE http://localhost:3001/api//blogs/4

###
POST http://localhost:3001/api/blogs/
content-type: application/json

{
    "title":"Paul Muad'Dib Atreides",
    "author": "12345",
    "url": "http://www.dune.com",
    "likes": 9999
}