GET http://localhost:3001/api/blogs/
###
GET http://localhost:3001/api/blogs/3

###
GET http://localhost:3001/api//blogs/65edf641c2243b6a5dfad75b

###
DELETE http://localhost:3001/api//blogs/65edf641c2243b6a5dfad75b


###
DELETE http://localhost:3001/api//blogs/4

###
POST http://localhost:3001/api/blogs/
content-type: application/json

{
    "title":"Dune",
    "author": "12345",
    "url": "http://www.dune.com",
    "likes": 9999,
     "userId": "65f879e8b959243ad802760c"
}
###
GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username":"Paul",
    "name": "Paul Muad'Dib Atreides",
    "password": "LisanAlGaib"
}
###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username":"Baron",
    "name": "Baron Vladimir Harkonnen",
    "password": "GiediPrime"
}

