GET http://localhost:3001/api/blogs/
###
GET http://localhost:3001/api/blogs/3

###
GET http://localhost:3001/api/blogs/664256ed22b1ce26645b882e

###
DELETE http://localhost:3001/api/blogs/65edf641c2243b6a5dfad75b


###
DELETE http://localhost:3001/api/blogs/664256ed22b1ce26645b882e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhcm9uIiwiaWQiOiI2NWY4N2IzZGJiNzczYzU1MjExMGI1ZmUiLCJpYXQiOjE3MTUxMDM1MDZ9.EkB7P3sZuD2UlEor7lP8-Vymndl_tI8zQiT0e4nfNVc 

###
POST http://localhost:3001/api/blogs/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhcm9uIiwiaWQiOiI2NWY4N2IzZGJiNzczYzU1MjExMGI1ZmUiLCJpYXQiOjE3MTUxMDM1MDZ9.EkB7P3sZuD2UlEor7lP8-Vymndl_tI8zQiT0e4nfNVc 

{
    "title":"Dune",
    "author": "12345",
    "url": "http://www.dune.com",
    "likes": 9999,
     "userId": "65f879e8b959243ad802760c"
}
###
GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username":"Paul",
    "name": "Paul Muad'Dib Atreides",
    "password": "LisanAlGaib"
}
###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username":"Baron",
    "name": "Baron Vladimir Harkonnen",
    "password": "GiediPrime"
}
###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username":"Baron",
    "password": "GiediPrime"
}


